<div class="card-body">
	<dl class="row">
		<dt class="col-sm-3">id:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.id}</dd>
		<dt class="col-sm-3">币种编码:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.coinCode}</dd>
		<dt class="col-sm-3">更新时间毫秒:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.lastUpdatedMillis}</dd>
		<dt class="col-sm-3">价格更新时间:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.lastUpdated?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">当前价格（USD）:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.price}</dd>
		<dt class="col-sm-3">24小时交易量:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.volume24h}</dd>
		<dt class="col-sm-3">24小时交易量变化:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.volumeChange24h}</dd>
		<dt class="col-sm-3">价格1小时变化比:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.percentChange1h}</dd>
		<dt class="col-sm-3">价格24小时变化比:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.percentChange24h}</dd>
		<dt class="col-sm-3">价格7天变化比:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.percentChange7d}</dd>
		<dt class="col-sm-3">价格30天变化比:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.percentChange30d}</dd>
		<dt class="col-sm-3">市值:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.marketCap}</dd>
		<dt class="col-sm-3">市场占有率:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.marketCapDominance}</dd>
		<dt class="col-sm-3">稀释后市值:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.fullyDilutedMarketCap}</dd>
		<dt class="col-sm-3">创建时间:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.createTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">修改时间:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.updateTime?string('yyyy-MM-dd HH:mm:ss')}</dd>
		<dt class="col-sm-3">备注:</dt>
		<dd class="col-sm-9">${coinmarketcapQuotes.comments}</dd>
	</dl>
</div>
